plugins {
    id 'com.android.application'
}
def runNumber = System.getenv("GITHUB_RUN_NUMBER")
def previewNumber = runNumber != null ? runNumber.toInteger() : 2

android {
    namespace 'dev.islandone.app'
    compileSdk 35
    defaultConfig {
        applicationId 'dev.islandone.app'
        minSdk 29
        targetSdk 35
        versionCode 200 + previewNumber
        versionName "0.2.${previewNumber}"
    }
    buildFeatures {
        buildConfig true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
